version: 0.{build}
image: Visual Studio 2017

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./LinqTranslator.sln --verbosity m

build_script:
  - cmd: dotnet publish ./LinqTranslator.sln

artifacts:
  - path: ./LinqTranslator/bin/Debug/netstandard1.0/publish
    name: DotNetStandard1_0
    type: zip
